### ISSUE TITLE
tracking: GHASH

### ISSUE THREAD

**Issue by thor314** [pluto/aes-proof#16]
Implement GHASH as specified in section 6.4 of the [NIST spec](https://nvlpubs.nist.gov/nistpubs/legacy/sp/nistspecialpublication800-38d.pdf)
- [x] #42 
- [x] #43 
- [x] #25 
- [x] #26 
- [x] #52
- [ ] #53

**Comment by thor314** [comment]
Still need to debug why GFMUL produces values 256 * what is expected, and test new polynomial, intermediate merge in PR #36.

**Comment by thor314** [comment]
@0xJepsen why did you close this?

**Comment by 0xJepsen** [comment]
> Still need to debug why GFMUL produces values 256 * what is expected, and test new polynomial, intermediate merge in PR #36.

Shall we make a new issue for it
