### ISSUE TITLE
misc: Circom compiler is not deterministic pre 2.1.9

### ISSUE THREAD

**Issue by dcbuild3r** [pluto/aes-proof#30]
The `circom` compiler used to create a non-deterministic R1CS layout pre `v2.1.9` because the assignment order of anonymous components inputs had non-determinism. Therefore if someone wants to verify an onchain verifier from the source code they won't be able to recreate it using the `snarkjs` toolchain because the `.zkey` file created after the output of the phase2 of the trusted setup procedure is dependent on the R1CS layout of the circuit which is nondeterministic. Anyone like [L2beat's ZK Catalog](https://l2beat.com/zk-catalog) will be able to reproduce the entire circuit from the circom source code all the way to the trusted setup and the verifier if we use the `pragma 2.1.9` declaration in all `.circom` files.

**Comment by 0xJepsen** [comment]
Nice do you want to change our compiler versions in our circuits now they they are somewhat constrained and solidified?

**Comment by dcbuild3r** [comment]
🫡
