### ISSUE TITLE
test: Vanilla AES-128

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/aes-proof#31]
Test vanilla aes-128 circuit in https://github.com/pluto/aes-proof/blob/main/circuits/aes/aes_256_encrypt.circom

This should fail initially because it is a 256 bit implementation

This can involved testing it's components:
- [row_shifting](https://github.com/pluto/aes-proof/blob/main/circuits/aes/aes_emulation.circom)
- [substitution box](https://github.com/pluto/aes-proof/blob/main/circuits/aes/aes_emulation.circom)

**Comment by Autoparallel** [comment]
Testing the components. Will not set up an AES test itself.
