### ISSUE TITLE
feat: Add snarkjs+wasm proving support

### ISSUE THREAD

**Issue by devloper** [pluto/aes-proof#5]
The base repo uses arkworks-compat for circom proving, it's a pretty non-standard approach, but for the sake of skipping javascript, I did it this way. 

For production, we will most likely want to prepare this repo to run in wasm with snarkjs. That'll require additional logic. However, due to the complexity of AES, it may make sense to keep that logic in rust. Then we can share packages with our proxy. 

Further, if we decide to keep the circom approach, we will need some sophisticated logic to load the 100MB+ vkeys.

**Comment by 0xJepsen** [comment]
Closing as completed
