### ISSUE TITLE
implement `mulx` based tests as mentioned in ietf spec appx A

### ISSUE THREAD

**Issue by thor314** [pluto/aes-proof#52]

**Comment by 0xJepsen** [comment]
This one should be closed by now i think

**Comment by thor314** [comment]
i meant that we could try implementing polyval in terms of the mul-x and reverse bytes, which is not yet implemented, sorry for not being clearer. See appx a; this is at best supplementary testing and low priority.

**Comment by brunny-eth** [comment]
---
name: implement ghash using mul-x and byte reversal
about: implement alternative version of ghash using mul-x and byte reversal as described in appendix A of the IETF AES-GCM implementation
title: implement ghash using mul-x and byte reversal
labels: Bounty 💰
assignees: 

---

**Bounty description**

Implement an alternative version of GHASH using the mul-x operation and byte reversal as described in Appendix A of the IETF AES-GCM spec. This implementation will be used for supplementary testing to validate the existing GHASH implementation in the AES-proof repo.

**Implementation requirements**

- [ ] Implement ByteReverse function
- [ ] Implement mulX_GHASH function
- [ ] Implement mulX_POLYVAL function
- [ ] Implement GHASH in terms of POLYVAL using spec
- [ ] Create unit tests to verify correctness of the implementation, using test vectors from IETF spec
- [ ] Document implementation
     
**Bonus features**

- [ ] Implement performance benchmarks to compare existing implementation with this one

**Resources**

[AES-GCM-SIV IETF Draft (Appendix A)](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-gcmsiv-08#appendix-A)
[NIST SP 800-38D (GCM)](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf)

**Criteria**

Bounties will be rewarded based on the following criteria:

1. Correctness and security: A thorough review of the implementation should convince our team that they are correct and secure, with all requirements met.
2. Code clarity and quality: Succinct, easy-to-follow code with appropriate naming conventions. Utilize Rust’s type system for flexibility and security (e.g., compile-time checks where possible), and avoid external crates. Optimizations should be a lower priority than clarity, but can be included behind a feature flag as a bonus.
3. Documentation quality: Provide comprehensive README’s, Cargo docs, and inline comments where code itself is not self-explanatory. Prioritize clarity and readability.

**Comment by brunny-eth** [comment]
@thor314  this is my attempt at turning this into a proper bounty, please provide feedback or update the issue with this if appropriate!

cc: @Autoparallel + @0xJepsen

**Comment by 0xJepsen** [comment]
@brunny-eth this one thor and i are working on so i am not sure it's well suited for a bounty mainly because we have already invested a good amount of time into it ourselves

**Comment by brunny-eth** [comment]
ok cool, no problem at all. can you call out 1-3 others in this repo that might make sense to have as issues for contributors instead?
