### ISSUE TITLE
benchmark and optimize ghash

### ISSUE THREAD

**Issue by thor314** [pluto/aes-proof#53]
At this point, we will have a naive ghash implementation, and one based on polyval. one will be faster. There may also be impromevents to intermediate template circuits.

**Comment by brunny-eth** [comment]
---
name: benchmark and optimize ghash
about: optimize and compare the existing ghash implementations for our AES-GCM proof in Circom
title: benchmark and optimize ghash
labels: Bounty 💰
assignees: 

---

**Bounty description**

Optimize and compare the existing GHASH implementations. We currently have a naive GHASH implementation and one based on Polyval. The goal is to further optimize both implementations, analyze their performance characteristics, and identify potential improvements in intermediate template circuits. 

**Implementation requirements**

- [ ] Analyze and optimize the naive GHASH implementation
    - Identify bottlenecks and areas for improvements
    - Implement optimizations (while maintaining correctness)
    - Document changes and benchmark their impact on constraint count
- [ ] Analyze and optimize the naive Polyval-based GHASH implementation
    - Identify bottlenecks and areas for improvements
    - Implement optimizations (while maintaining correctness)
    - Document changes and benchmark their impact on constraint count
- [ ] Implement thorough testing suite and documentation
    - Ensure correctness is maintained after optimizations
    - Verify against standard test vectors for AES-GCM     
    - Create detailed documentation of optimizations and findings

**Bonus features**

Any additional features that will enhance the value of the bounty. 

- [ ] Conduct a more comprehensive performance comparison between the approaches
    - Compare constraint counts for both implementations
    - Analyze proving time and proof size for each approach
    - Evaluate trade-offs in a short but detailed write-up 
- [ ] Investigate and implement improvements to intermediate template circuits

**Resources**

[Circom Documentation](https://docs.circom.io/)
[NIST SP 800-38D (GCM mode)](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf)
[Polyval specification](https://datatracker.ietf.org/doc/html/rfc8452)
[Optimizing Arithmetic Circuits for ZKPs](https://www.zksecurity.xyz/blog/posts/optimizing-arithmetic-circuits/)

**Criteria**

Bounties will be rewarded based on the following criteria:

1. Correctness and security: A thorough review of the implementation should convince our team that they are correct and secure, with all requirements met.
2. Code clarity and quality: Succinct, easy-to-follow code with appropriate naming conventions. Utilize Rust’s type system for flexibility and security (e.g., compile-time checks where possible), and avoid external crates. Optimizations should be a lower priority than clarity, but can be included behind a feature flag as a bonus.
3. Documentation quality: Provide comprehensive README’s, Cargo docs, and inline comments where code itself is not self-explanatory. Prioritize clarity and readability.

**Comment by 0xJepsen** [comment]
This could be a good bounty but i feel it's something that might have security implications so it may be best to work on this ourselves.
