### ISSUE TITLE
question: main entry point and output

### ISSUE THREAD

**Issue by Autoparallel** [pluto/aes-proof#61]
For us to use this in the `web-prover` stack, we're going to need a main entrypoint here (even if it is parameterized by data size in some way). 

Also, for decryption, we need this to output the raw bytes of an HTTP response so that we can feed that into the HTTP parser.

Can we set up these entry/exit points?

**Comment by 0xJepsen** [comment]
First steps in my opinion are to build the aes-gcm entry point. We are finishing the exterior ghash template here #62 and aim to have the aes-gcm one done next week. The aes-gcm template will take in a 128-bit key and 128bit blocks of ciphertext (likely parameterized by the number of blocks) and product the proof that the key decrypts this cipher text.

**Comment by 0xJepsen** [comment]
Closed as completed with the AES Fold circuit
