### ISSUE TITLE
Solidity contract verifier

### ISSUE THREAD

**Issue by mattes** [pluto/aes-proof#64]
Export a solidity contract verifier. It looks like circomkit has a nice feature for it as well.

Nice to have: Export it as Github CI artifact.

**Comment by 0xJepsen** [comment]
So i looked into this a bit and i think a prerequisite is for use to agree on a powers of tau file and a trusted setup for the test net. Once we have agreed to use one across our circuits we can generate a solidity verifier.

**Comment by 0xJepsen** [comment]
Closed as no longer related to these circuits
