### ISSUE TITLE
feat: Investigate security of The AES components

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/aes-proof#88]
The may be some security considerations outlined in the crema labs work in this PR https://github.com/crema-labs/aes-circom/pull/7, we should pull the downstream changes and also investigate their constraints carefully.

**Comment by 0xJepsen** [comment]
Looks like SBOX is not constrained at all https://github.com/pluto/aes-proof/blob/038453186a355d40520608c0d1f7b9140c40ecb5/circuits/aes-gcm/aes/sbox128.circom#L10-L29

**Comment by thor314** [comment]
@0xJepsen have you looked into this any further?

**Comment by 0xJepsen** [comment]
yes this is done with sambav early
